server:
  port: 9001

# 数据库连接
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?characterEncoding=utf-8&serverTimezone=GMT
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver

# mybatis-plus
mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  type-aliases-package: com.mqs.entity
  global-config:
    db-config:
      id-type: auto
      field-strategy: ignored